sudo: false
language: node_js
services:
- docker
node_js:
- 7.4.0
env:
  matrix:
  - CXX=g++-4.8
  global:
  - DOCKER_IMAGE_NAME=kimwijk/earlycorn
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: du4aZRyJde09E6aFT8R3LW7eFemM44sLAOnTxiHZmMecdvmXmUZawD6uSQwncJvMg05TZ+022k2T4iYtH4IjjeqK9JQ5Ox+scQbNZY+69GoZaQ2dFWmu++iwuGNTP76r3mE84lGrIFmnd/2m6GI4JfdTO2v7jYil6e4p/zboTW3V/ue0vBSJjCFthuCxIpSrM06kKmTz1q5UdzwS+CJj1NzDE5S7SAv8JnTRDgIC0wJ/6QWLsnMiopJkFAVsDLuVdUaIzdnjTyFo5eNwYZJGUhYb4ohMkXOW5CDL71Kpgp5u7zpZmLHFVvyRLtSHLma3ctmAGwPJDX+D3FhmesLIhUirZLSRGpnF4QvVvnqO/3SVg4GpJZQSS4/PNpjYJjfML6y6R4gDdDRBH1qYjx6FDHG4dHRNcnxMZ2tNpk5012QYF67jaeXjVAywslLLbtt7kmEfioxfs+mHjWo8lXLeiB69zoHSCKMyTRccMcATqKF6btSzxIZj06SOOrNBa5/NuqghD6JtOdFEZoKj0bPFCtYZhALBpkPAG3RHNX/mcI44ZG78sts4Idd7KTzrxDSGKNyd+08mjyjInTOQb4Mn69Fcrbi0eh7kAFGkDst8gDugRiKxvuf+KgnECr9cGa1sMjgSA2J0pqUlqPV92NlkjpR9k+7sYb2TsJyn06Seo/Y=
  - secure: CKS3snM9GDAr9DHmSLLVqrEA/xSrp3AN3hB4SQJfoZlC33gcm/pECQlwdHz2PdYmzOPwDFhD+5pJywOh8wf5tnd2SgEDZibzWnspEohttXcEEcW8+Lf/T/NL5mslVmQd8FquUrfGjDKrgQaQlDBcNkTmpVll8qsk2cPBHcddt83OeFsfId9a6zpAfLZj3CQN0Z7CncB3iXlWbuGt7SB7vyzDYrLWRAPKqWilNDaIwNo2OydbiLZf20hCP5qMj0PIC9f5nFHLRws3+/WfqnrYsvT5DR1BVUdtJ06HEOUIY977AZFp4TCUnNRoOg/9PdVOZbBCenehibVDfBcneDoKGManho+yrE9+J8g9FxeOKRVlcoFrUM+VldHL+YFFjFPsk400O0P8NbYgMRIrC5b1H4SZRfKqrhSQthYH2woMlnXHx/MGFjKqLhIRvoeIlAQA4z5axGyAPTIM9fXQuedGDTEZjCK755XBuC2oyu6ZFaYFpKOLINroiLVMrHufnRUvOSNdsDFlcq8mSO72L0ZMgc/ejgUudFDJwwru1ckRr4RZ/lbn3q3tTivq/b9iZXYrLfE73HRXyUBDS4WaS+vhZznEzwqOlCJPEQ3U05zfbVW+CwErCVcTmzSEwV6qqOGKNSQM38yQ1p0iR9ApwR6njh31aosJuaygbj1yrVPTJyk=
  - secure: as6WvTr8+ixUeToEZ/ThTjuEsTd5Jtd8psUgKF2BqIfaq9YA+Q0jkh2tS/b3YP/Rr1oHTy7w+QYPQsP7CpVKplsB7nB68mvhAWMjCAxJVYjQf1wvGP6DrWLq7zcQddBs/xlPCqRqkMOY1nRqJ0fneADhx3m3IdhJ6J4w8vpF2eJWP2UF3Dk/yNr/AyqWOxQx3q9oio1IatTULul9LHSieVlnzRlRLiYhzeIqD6k3UIh09j049ixB9X7CBBkU27SuYGEgu2SgY6mh7iDJQgd8Al/Y4cjyoqYCUTjSjSxPRajWxzV0LhwttgHByPGFNlxSlRqAOO5JvLSOdFkFif3QnY38kuwrJIak9TsoUIJr45H2aBsMOIj9LrFN9T6JJ8YApN/tAnKFpX/xCUfnjIUkVJCB3UjeHhxI/itdCXc0URvWD39sZ2Bn1bF2LtpMvThD0GKDYuv8Kw+F+VTlUdrtRfn7+p/+5MOHxs8hkhV3S8s7ejx0teRRz/Ao24Mt4mQvKukE1Q3uz1HX4Z301QEAYCiBfEVvJt8vTJVwChi58tmTQsX160MKq4ZYuon3qLFrDCpzBMFh+Z5nCGUIHaiAHnBqv3essW3LzLWqujH3F3LmyifB/Ai7g7XHLMX6t4LSkdKvDid6zoFOhKsdiSfSnXgJt7von6JN9nSoj/GU6nk=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker build -f Dockerfile -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $DOCKER_IMAGE_NAME; fi
